// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using future_1_.Data;

namespace future_1_.Migrations
{
    [DbContext(typeof(FutureDbContext))]
    partial class FutureDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("future_1_.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiseaseFreeCert_PH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLicense_PH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NonConvictionCert_PH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityPermit_PH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransportationEntityId")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverId");

                    b.HasIndex("TransportationEntityId");

                    b.ToTable("drivers");
                });

            modelBuilder.Entity("future_1_.Models.Fleet", b =>
                {
                    b.Property<int>("FleetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorityPermit_PH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackBus_license_PH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BoardNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("FleetState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontBus_license_PH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("TransportationEntityId")
                        .HasColumnType("int");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("effectiveness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fleetModel")
                        .HasColumnType("int");

                    b.Property<string>("fleetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FleetId");

                    b.HasIndex("DriverId")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.HasIndex("TransportationEntityId");

                    b.ToTable("fleets");
                });

            modelBuilder.Entity("future_1_.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("regions");
                });

            modelBuilder.Entity("future_1_.Models.School", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolId");

                    b.HasIndex("RegionId");

                    b.ToTable("schools");
                });

            modelBuilder.Entity("future_1_.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("students");
                });

            modelBuilder.Entity("future_1_.Models.TransportationEntity", b =>
                {
                    b.Property<int>("TransportationEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransportationEntityId");

                    b.HasIndex("RegionId");

                    b.ToTable("transportationEntities");
                });

            modelBuilder.Entity("future_1_.Models.TransportationEntityAndSchoolRel", b =>
                {
                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int>("TransportationEntityId")
                        .HasColumnType("int");

                    b.HasKey("SchoolId", "TransportationEntityId");

                    b.HasIndex("TransportationEntityId");

                    b.ToTable("TRS_Rel");
                });

            modelBuilder.Entity("future_1_.Models.Driver", b =>
                {
                    b.HasOne("future_1_.Models.TransportationEntity", "trEntity")
                        .WithMany()
                        .HasForeignKey("TransportationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("trEntity");
                });

            modelBuilder.Entity("future_1_.Models.Fleet", b =>
                {
                    b.HasOne("future_1_.Models.Driver", "driver")
                        .WithOne("fleet")
                        .HasForeignKey("future_1_.Models.Fleet", "DriverId")
                        .IsRequired();

                    b.HasOne("future_1_.Models.Region", "region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("future_1_.Models.TransportationEntity", "transportationEntity")
                        .WithMany("fleets")
                        .HasForeignKey("TransportationEntityId")
                        .IsRequired();

                    b.Navigation("driver");

                    b.Navigation("region");

                    b.Navigation("transportationEntity");
                });

            modelBuilder.Entity("future_1_.Models.School", b =>
                {
                    b.HasOne("future_1_.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("future_1_.Models.TransportationEntity", b =>
                {
                    b.HasOne("future_1_.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("future_1_.Models.TransportationEntityAndSchoolRel", b =>
                {
                    b.HasOne("future_1_.Models.School", "school")
                        .WithMany("transportationEntityAndSchoolRels")
                        .HasForeignKey("SchoolId")
                        .IsRequired();

                    b.HasOne("future_1_.Models.TransportationEntity", "transportationEntity")
                        .WithMany("transportationEntityAndSchoolRels")
                        .HasForeignKey("TransportationEntityId")
                        .IsRequired();

                    b.Navigation("school");

                    b.Navigation("transportationEntity");
                });

            modelBuilder.Entity("future_1_.Models.Driver", b =>
                {
                    b.Navigation("fleet");
                });

            modelBuilder.Entity("future_1_.Models.School", b =>
                {
                    b.Navigation("transportationEntityAndSchoolRels");
                });

            modelBuilder.Entity("future_1_.Models.TransportationEntity", b =>
                {
                    b.Navigation("fleets");

                    b.Navigation("transportationEntityAndSchoolRels");
                });
#pragma warning restore 612, 618
        }
    }
}
